version: "3.8"

services:
  mockoon:
    image: mockoon/cli:latest
    # Descomenta esta línea si usas Mac M1/M2/M3 (para forzar compatibilidad)
    # platform: linux/amd64
    command:
      - --data
      - /data/mock.json
      - --hostname
      - 0.0.0.0
      - --port
      - "3000"
      - --log-transaction
      - --repair
    volumes:
      - ./tests/openweather_mock.json:/data/mock.json:ro
    ports:
      - "3000:3000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "node -e \"http=require('http');http.get('http://localhost:3000/health',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1));\""
        ]
      interval: 3s
      timeout: 2s
      retries: 20
    restart: unless-stopped

  splunk:
    image: splunk/splunk:9.4.1
    # Necesario en Mac ARM (M1/M2/M3)
    platform: linux/amd64
    environment:
      SPLUNK_START_ARGS: --answer-yes --no-prompt --accept-license
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD:-password}
      SPLUNK_USER: root
    volumes:
      # Asegúrate de haber ejecutado 'ucc-gen build' antes de iniciar los contenedores
      - ./output/${APP_NAME:-ta_tdd_demo}:/opt/splunk/etc/apps/${APP_NAME:-ta_tdd_demo}:ro
    ports:
      - "8000:8000"   # Web UI
      - "8089:8089"   # API Management
    depends_on:
      mockoon:
        condition: service_healthy
    restart: unless-stopped
