# .github/workflows/pr-tests.yml
name: PR Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Start services
        run: docker compose up -d app mockoon
      - name: Wait for services
        run: |
          for i in {1..30}; do
            (curl -sf http://localhost:8000/health && curl -sf http://localhost:3000/api/greeting) && break || sleep 2
          done
      - name: Run unit+integration tests (in containers)
        run: docker compose run --rm tests
      - name: Teardown
        if: always()
        run: docker compose down -v